use_frameworks!

target 'SuggestionsBox_Example' do
  pod 'SuggestionsBox', :path => '../'
  pod 'Firebase'

  target 'SuggestionsBox_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  end
end
