platform :ios, '8.0'
use_frameworks!

target 'SuggestionsBox_Example' do
  pod 'SuggestionsBox', :path => '../'
end

target 'SuggestionsBox_Tests' do
  pod 'SuggestionsBox', :path => '../'
  pod 'Quick', '~> 0.8'
  pod 'Nimble'
end
